### ISSUE TITLE
[IMPROVE] Handoff API endpoint to accept buttonID as an optional arg

### ISSUE THREAD

**Issue by dlassalle** [RocketChat/Apps.Salesforce.LiveAgent#12]
Update handoff api endpoint to accept a buttonID as an optional arg to route the handed-off chat to instead of the one configured in the app settings

**Comment by PrajvalRaval** [comment]
Please close this issue, since you already approved it 😉

**Comment by dlassalle** [comment]
Ah good reminder, thanks
